### ISSUE TITLE
Modularize Notifications

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#653]
With the new email features and changes coming, it might be important to put all these email functions as a new module (app?) like `printing`. This would allow for more abstraction of the forms and the functions provided. This task is branched off #644, and inspired with @czlee's FB post liked in #652.

For this app (`notifications`?), there are a few main points:
* [x] Be able to set name/reply-to for all emails (#644)
* [x] Insert headers/metadata to emails
* [x] Better mail-merge (rather than the forest of `replace`)
* [x] Keep record of sent messages (à la `privateurlsentmailrecord`) (mentioned in #626)
  * [ ] Avoid duplicate notifications
* [ ] Support alternatives to emails (#652)
* [x] HTML-type emails (#800)
* [x] ~Easy "unsubscribe"~

Point 2 would be for information as to why the message is sent could be attached, along with an opt-out or something (that would get into dynamic_preferences I guess).

For point 3, that table could perhaps be generalized to something like `notifications_log` with a structure:

Field | Type | Notes
------|-----|-----
id | INT PRIMARY
person | INT FOREIGN | `participants_person`
event | VARCHAR (ENUM?) | What type of email was sent (_e.g._ 'ballot_confirmed')
timestamp | DATETIME
method | VARCHAR (ENUM?) | email or other enabled method
round | INT FOREIGN NULL | `tournaments_round` - As most notifications are round-specific, like 'ballot_confirmed'.

Some of the cruft is left off, such as different fields for adj/speaker, nor are the contents of the email in the table as they could be easily re-constructed from the other data (I'd think).

**Comment by czlee** [comment]
This is a good idea, I was thinking about it too. One dumb question before we get too far in though: Does there exist a third-party Django app that does something similar to what we want? This isn't really a debating-specific problem, and we can't be the first people to want to send a bunch of automated template emails at particular user-triggered times and keep records of it.

By analogy—when we were figuring out how to overhaul options the first time we found django-dynamic-preferences, and now we rely on it and it's been really helpful.

I also agree that once we have other email sent mail records, the `PrivateUrlSentMailRecord` model should be removed and merged into a more generic `SentMailRecord` or `NotificationLog` like the one you describe in this table. (Or the third-party app's records, if they exist.)

(I did a quick search but it's surprisingly nontrivial to get the search terms right because "django email" just returns a bunch of pages that describe how to send emails in Django! Here's a page listing lots of potentially relevant apps, albeit not necessarily ones that suit our needs: https://djangopackages.org/grids/g/email/)

**Comment by tienne-B** [comment]
I have not found any app that would make sending these messages that much better. To get point 1, 2, and 4, a subclass of `EmailMessage` (or `EmailMultiAlternatives`) could be made to specify general information that is relevant to all TC emails.

Personally, HTML is not worth it for emails. Plain-text is usable everywhere, and my design, especially for the safe-email subset is bad.

**Comment by czlee** [comment]
Yeah, I looked once or twice more, there are so many emailing apps and none of them seem to hit _quite_ what we want. Kind of amazing, really.

It might seem redundant at first glance, but I think it's a good idea to include (at least) two more fields in `MessageSentRecord`:

1. The email address the notification was sent to (the equivalent of the old `PrivateUrlSentMailRecord.email`). This shouldn't be assumed to match the email address of the `recipient`, because it might have been corrected after an email was sent (to the wrong address), or changed for some other reason. You want the records to reflect what _actually_ happened.

2. A field for any details included in the email. For private URL emails this means the URL key, or maybe even the whole URL. For team point or win-loss records, this means the team point count or wins count that was sent (again, in case it gets corrected later). For result confirmations, this means the scores that were sent.

   Obviously, the fact that these differ between notification types makes this a bit annoying. There are generally two paradigms for this: (a) to make other models in the relevant individual apps, linked to sent mail records by `OneToOneField`s, or (b) to make this field a `CharField` with arbitrary text, and it's on individual apps to interpret it correctly.

   (a) is more structured and so less prone to user interference (by editing the field), but entails more infrastructural overhead; while (b) is more prone to user interference but makes for a simple database schema. I'd favor (b), but I'm open to arguments for (a).

   Both (1) and (2) also help with the filters that prevent it from sending the same email twice. If you change an email address or a URL key, then the sent mail filter would detect that something has _not_ been sent with the _new_ email address/URL key, and will proceed to send a message there when sending the next round of emails.

3. Since the email template itself can now be customized, I wonder if we should also just store the entire message as well? Just in case there's doubt about the text that was actually sent. If we did do this, it sadly couldn't _replace_ the details field in (2) above, because we'd still need (2) to do lookups effectively.

Lastly, just me being picky about a small detail: Can we call it `SentMessageRecord` rather than `MessageSentRecord`? This seems more idiomatic to me. 🙂

**Comment by czlee** [comment]
The context field is great but I think we want to be able to run SQL filters on it somehow. I don't have a firm solution in mind, though I'm thinking we probably want this to be set explicitly by the caller rather than auto-populated from the message object?

For example, for URL keys, I think the desired behaviour should be as follows:
- If a participant's URL key changes (and so differs from the sent message record), the `RandomisedUrlsMixin.get_participants_to_email()` method should include them in the list, so that they will be sent their new URL key.
- If a participant's email changes (and so differs from the sent message record), the `RandomisedUrlsMixin.get_participants_to_email()` method should include them in the list, so that their new email address will be sent the URL key.

The sort of use case I have in mind is if there's a typo in the email address that only gets discovered after the main batch of private URLs have been sent. The tab director shouldn't have to delete the sent message record to get Tabbycat to detect that the participant hasn't been sent an email.

This is the old behaviour, see: https://github.com/TabbycatDebate/tabbycat/blob/6db2eb582ecb88a63e0bb8eec38d7ef285fabbb2/tabbycat/privateurls/views.py#L37-L40

https://github.com/TabbycatDebate/tabbycat/blob/6db2eb582ecb88a63e0bb8eec38d7ef285fabbb2/tabbycat/privateurls/views.py#L52-L55

For email we can do this filter already, but for the URL key it's a bit harder, because you have to get it to parse through the contents of the JSON-like text. I'm sure it's doable in principle, but the only method I can think of (using SQL's `LIKE`) is subject to edge cases, and to me this is the only real purpose of the context field.

By analogy, if a team's team point count has changed (for the same round, due to an amended result), I think if we had a filter that prevents sending duplicate emails, that filter should allow the changed team's team point email to be sent.

Does that make sense?

(To avoid doubt—I don't think this change should require a migration. But I could be wrong.)

**Comment by tienne-B** [comment]
Yes, the `email` can be compared quite easily. For non-matching URL keys, `context__URL` can be used (as it is a PostgreSQL `JSONField`) I'll take a closer look later.

**Comment by philipbelesky** [comment]
Just a quick note that I'm bumping this to the L-release; it looks like the remaining items on the checklist are enhancements but the core modularisation is done and good enough to ship.

**Comment by philipbelesky** [comment]
Looks like duplicates are in, is this good to close then? @tienne-B
